apiVersion : apps/v1
kind: Deployment
metadata:
  name: weighttrackercicdks 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weighttrackercicdks
  template:
    metadata:
      labels:
        app: weighttrackercicdks 
    spec:
      containers:
        - name: weighttrackercicdks 
          image: weighttrackeracr.azurecr.io/weighttrackercicdks:latest
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8080
            protocol: TCP
          envFrom: 
          - configMapRef:
             name: weighttracker-cm.yml
          - secretRef:
             name: weighttracker-secrets.yml
