apiVersion : apps/v1
kind: Deployment
metadata:
  name: renattsweighttrackerks 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: renattsweighttrackerks
  template:
    metadata:
      labels:
        app: renattsweighttrackerks 
    spec:
      containers:
        - name: renattsweighttrackerks 
          image: weighttrackeracr.azurecr.io/renattsweighttrackerks
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            protocol: TCP
          env:         
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: HOST
          - name: OKTA_ORG_URL
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: OKTA_ORG_URL
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: NODE_ENV      
          - name: PGPORT
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: PGPORT
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: PGHOST      
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: PORT     
                
          - name: HOST_URL
            valueFrom:
              secretKeyRef:
                name: weighttracker-secrets
                key: HOST_URL         
          - name: OKTA_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: weighttracker-secrets
                key: OKTA_CLIENT_ID
          - name: OKTA_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: weighttracker-secrets
                key: OKTA_CLIENT_SECRET
          - name: COOKIE_ENCRYPT_PWD
            valueFrom:
              secretKeyRef:
                name: weighttracker-secrets
                key: COOKIE_ENCRYPT_PWD
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: weighttracker-secrets
                key: PGDATABASE
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: weighttracker-secrets
                key: PGPASSWORD
          - name: PGUSERNAME
            valueFrom:
              secretKeyRef:
                name: weighttracker-secrets
                key: PGUSERNAME
