apiVersion : apps/v1
kind: Deployment
metadata:
  name: renattsweighttrackerks 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: renattsweighttrackerks
  template:
    metadata:
      labels:
        app: renattsweighttrackerks 
    spec:
      containers:
        - name: renattsweighttrackerks 
          image: weighttrackeracr.azurecr.io/renattsweighttrackerks
          ports:
          - containerPort: 80
            protocol: TCP
          env:         
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: HOST
          - name: OKTA_ORG_URL
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: OKTA_ORG_URL
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: NODE_ENV      
          - name: PG_PORT
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: PG_PORT
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: weighttracker-cm
                key: PORT     
                
          - name: HOST_URL
            valueFrom:
              secretKeyRef:
                name: secrets
                key: HOST_URL         
          - name: OKTA_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: secrets
                key: OKTA_CLIENT_ID
          - name: OKTA_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: OKTA_CLIENT_SECRET
          - name: COOKIE_ENCRYPT_PWD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: COOKIE_ENCRYPT_PWD
          - name: PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: secrets
                key: PG_DATABASE
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: secrets
                key: PG_HOST
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: PG_PASSWORD
          - name: PG_USERNAME
            valueFrom:
              secretKeyRef:
                name: secrets
                key: PG_USERNAME
