apiVersion: v1
kind: Service
metadata:
    name: renattsweighttrackerks
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    selector:
        app: renattsweighttrackerks
