apiVersion: v1
kind: Service
metadata:
  name: renattsweighttrackerks
  labels: 
    app: renattsweighttrackerks
spec:
    type: ClusterIP
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    selector:
        app: renattsweighttrackerks
